In [7]:
import pandas as pd
import numpy as np
import sklearn


In [3]:
import sklearn
from sklearn.datasets import load_boston
bd = load_boston()


C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the Californi

In [4]:
bd.keys()


dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename', 'data_module'])

In [5]:
print(bd.data)


[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [15]:
boston = pd.DataFrame(bd.data, columns=bd.feature_names)
boston.tail(2)


CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
504  0.10959  0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741  0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88

In [18]:
boston['target'] = bd.target  # in 1000's
boston.tail(2)


CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
504  0.10959  0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741  0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  target  
504     21.0  393.45   6.48    22.0  
505     21.0  396.90   7.88    11.9

In [20]:
boston.isnull()


CRIM     ZN  INDUS   CHAS    NOX     RM    AGE    DIS    RAD    TAX  \
0    False  False  False  False  False  False  False  False  False  False   
1    False  False  False  False  False  False  False  False  False  False   
2    False  False  False  False  False  False  False  False  False  False   
3    False  False  False  False  False  False  False  False  False  False   
4    False  False  False  False  False  False  False  False  False  False   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
501  False  False  False  False  False  False  False  False  False  False   
502  False  False  False  False  False  False  False  False  False  False   
503  False  False  False  False  False  False  False  False  False  False   
504  False  False  False  False  False  False  False  False  False  False   
505  False  False  False  False  False  False  False  False  False  False   

     PTRATIO      B  LSTAT  target  
0      False  False  False   False  
1      False  False  False   False  
2      False  False  False   False  
3      False  False  False   False  
4      False  False  False   False  
..       ...    ...    ...     ...  
501    False  False  False   False  
502    False  False  False   False  
503    False  False  False   False  
504    False  False  False   False  
505    False  False  False   False  

[506 rows x 14 columns]

In [22]:
boston.isnull().sum()


CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
target     0
dtype: int64

In [125]:
from calendar import c
from sklearn.model_selection import train_test_split
x = boston.drop('target', axis=1)
y = boston['target']
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=.05, random_state=5)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)


(480, 13)
(26, 13)
(480,)
(26,)


In [120]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
regressor = LinearRegression()
regressor.fit(x_train, y_train)


LinearRegression()

In [127]:
y_train_predict = regressor.predict(x_train)
rmse = (np.sqrt(mean_squared_error(y_train, y_train_predict)))
print("tranning set")
print('RMSE is {}', rmse)

y_test_predict = regressor.predict(x_test)
rmse = (np.sqrt(mean_squared_error(y_test, y_test_predict)))
print("tranning set")
print('RMSE is {}', rmse)


tranning set
RMSE is {} 4.687031258532204
tranning set
RMSE is {} 4.620248519093883


In [1]:

import matplotlib.pyplot as plt
plt.figure ( figsize = ( 5,5 ) )
plt.scatter ( y_test , y_test_predict )
plt.plot ( [ min ( y_test_predict ) , max ( y_test_predict ) ] , [  min ( y_test_predict ) , max ( y_test_predict )])
plt.xlabel ( ' Actual ' )
plt.ylabel ( ' Predicted ' )



NameError: name 'y_test' is not defined

<Figure size 500x500 with 0 Axes>